# Generated by Django 3.2.8 on 2023-03-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('deferida_categoria', models.CharField(max_length=200)),
            ],
        ),
    ]
