# Generated by Django 3.2.8 on 2023-03-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='num_stars',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='categorioa',
            new_name='categoria',
        ),
    ]
